[keyboard]
name = "rmk-urchin"
product_name = "rmk-urchin"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
board = "nice!nano_v2"

[layout]
row2col = false
rows = 4
cols = 10
layers = 5
keymap = [
  [
    [
      "Q",
      "D",
      "R",
      "W",
      "B",
      "J",
      "F",
      "U",
      "P",
      "BSLS"
    ],
    [
      "A",
      "MT(S,LGUI)",
      "MT(H,LALT)",
      "MT(T,LCTL)",
      "MT(G,LSFT)",
      "MT(Y,RSFT)",
      "MT(N,RCTL)",
      "MT(E,RALT)",
      "MT(O,RGUI)",
      "I"
    ],
    [
      "Z",
      "X",
      "M",
      "C",
      "V",
      "K",
      "L",
      "COMMA",
      "DOT",
      "SLASH"
    ],
    [
      "_",
      "_",
      "_",
      "LT(2,ENTER)",
      "LT(1,TAB)",
      "LT(4,SPACE)",
      "LT(3,BACKSPACE)",
      "_",
      "_",
      "_"
    ]
  ],
  [
    [
      "GRAVE",
      "_",
      "_",
      "_",
      "_",
      "LEFT",
      "DOWN",
      "UP",
      "RIGHT",
      "WM(BSLS,RCTRL)"
    ],
    [
      "WM(GRAVE,RSFT)",
      "LGUI",
      "LALT",
      "LCTRL",
      "LSHIFT",
      "9",
      "1",
      "2",
      "3",
      "4"
    ],
    [
      "ESCAPE",
      "_",
      "_",
      "_",
      "_",
      "0",
      "5",
      "6",
      "7",
      "8"
    ],
    ["_", "_", "_", "_", "NO", "_", "_", "_", "_", "_"]
  ],
  [
    [
      "GRAVE",
      "_",
      "_",
      "_",
      "_",
      "_",
      "DELETE",
      "PGUP",
      "PGDN",
      "WM(BSLS,RCTRL)"
    ],
    [
      "_",
      "LGUI",
      "LALT",
      "LCTRL",
      "LSHIFT",
      "[",
      "MINUS",
      "EQUAL",
      ";",
      "QUOTE"
    ],
    [
      "ESCAPE",
      "_",
      "_",
      "_",
      "_",
      "]",
      "SHIFTED(MINUS)",
      "SHIFTED(EQUAL)",
      "SHIFTED(;)",
      "SHIFTED(QUOTE)"
    ],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
  ],
  [
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "MUTE",
      "VOLD",
      "VOLU",
      "MPLY",
      "MSTP"
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_"
    ],
    [
      "ESCAPE",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_"
    ],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
  ],
  [
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_"
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_"
    ],
    [
      "ESCAPE",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
      "_"
    ],
    ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
  ]
]

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0

[split.central.matrix]
row_pins = [
  "P1_00",
  "P0_11",
  "P1_04",
  "P1_06",
]
col_pins = [
  "P1_15",
  "P1_13",
  "P1_11",
  "P0_10",
  "P0_09",
]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5

[split.peripheral.matrix]
row_pins = [
  "P1_13",
  "P1_11",
  "P0_10",
  "P0_09",
]
col_pins = [
  "P0_24",
  "P1_00",
  "P0_11",
  "P1_04",
  "P1_06",
]

# [[split.peripheral]]
# rows = 2
# cols = 1
# row_offset = 2
# col_offset = 2
# serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
# row_pins = ["PIN_9", "PIN_11"]
# col_pins = ["PIN_10"]

[rmk]
split_peripherals_num = 1
ble_profiles_num = 3
debounce_time = 50

[host]
unlock_keys = [[0, 0], [0, 1]]
